### PR TITLE
hop-client 0.1 updates

### PR DESCRIPTION
**Pull request by myNameIsPatrick**
## Description

This PR makes updates to the codebase to comply with hop-client 0.1. It would be great if I can get verification for the gcn and tns services that they still work as expected with these changes as well. Also address a few issues from the linter.

## Checklist

* [x] All new functions and classes are documented and adhere to Google doc style (3.8.3-3.8.6 of [this](http://google.github.io/styleguide/pyguide.html#383-functions-and-methods) document)
* [x] Add/update sphinx documentation with any relevant changes.
* [x] Add/update pytest-style tests in `/tests`, ensuring sufficient code coverage.
* [x] `make test` runs without errors.
* [x] `make lint` doesn't give any warnings.
* [x] `make format` doesn't give any code formatting suggestions.
* [x] `make doc` runs without errors and generated docs render correctly.
* [x] Check that CI pipeline run on this PR passes all stages.
* [ ] Review signoff by at least one developer.

NOTE: If this PR relates to a release, open and reference an issue with the Release checklist template.

### CODE REVIEW

**Comment by myNameIsPatrick** [comment]
Forgot to mention in the original ticket: There were a few globals that seemed unused by that function now, so I removed them.

**Review by shereenElSayed — APPROVED** [review]
Code changes seem okay to me for TNS

**Comment by myNameIsPatrick** [comment]
Okay, great. The changes to the GCN section should be pretty innocuous as well. I rebased against your latest TNS changes as well and rebased them against this branch, which should make it compatible with the new client as well.

**Comment by myNameIsPatrick** [comment]
@rdt12, are you okay with these changes for the GCN client?

**Review by shereenElSayed — CHANGES_REQUESTED** [review]
I guess there are some slight changes that need to be addressed in scripts/tns_run.py
--The location for config file should be .TOML now

**Review by shereenElSayed — CHANGES_REQUESTED** [review]
In Utils.py,

I guess now we should have a different writing for config format other than that in lines 86 - 91:
````
    cfh.write("security.protocol=SASL_SSL\n")
    cfh.write("sasl.username=%s\n" % creds["user"])
    cfh.write("sasl.password=%s\n" % creds["pass"])
    cfh.write("sasl.mechanism=PLAIN\n")
    cfh.write("ssl.ca.location=/etc/pki/tls/certs/ca-bundle.trust.crt\n")
```

**Comment by myNameIsPatrick** [comment]
@shereenElSayed, thanks for catching that, those seem to be new changes in the rebase that I didn't see.

**Pull request merged**
