### PR TITLE
Various odds and ends

### PR DESCRIPTION
**Pull request by myNameIsPatrick**
## Description

This PR has a grab bag of different changes mostly related to the TNS side of the codebase:

* Fix CLI one-liner description for subparser commands (e.g. `stream2hop tns --help`).
* Rename `object` variable in various places in `tns2hop.py` to `object_` to not clash with reserved keyword.
* Expose passing of `parameters.json` as a command line option, via `--params-file`, which defaults to the previous location.
* Read `parameters.json` only once at the beginning.
* Reuse hop connection within `get_astronotes()`.
* Only process `astronotes_list` if it is non-empty. Turns out the REST API returns an empty list (versus an empty JSON object which gets maps to a dict), so calling `astronotes_list.items()` fails, and this will get around this issue.
* Revert permissions on random files that had execute access.

## Checklist

* [ ] All new functions and classes are documented and adhere to Google doc style (3.8.3-3.8.6 of [this](http://google.github.io/styleguide/pyguide.html#383-functions-and-methods) document)
* [ ] Add/update sphinx documentation with any relevant changes.
* [ ] Add/update pytest-style tests in `/tests`, ensuring sufficient code coverage.
* [ ] `make test` runs without errors.
* [ ] `make lint` doesn't give any warnings.
* [ ] `make format` doesn't give any code formatting suggestions.
* [ ] `make doc` runs without errors and generated docs render correctly.
* [ ] Check that CI pipeline run on this PR passes all stages.
* [ ] Review signoff by at least one developer.

NOTE: If this PR relates to a release, open and reference an issue with the Release checklist template.

### CODE REVIEW

**Comment by shereenElSayed** [comment]
For tns2hop, I don't have any comments so far, this clean touch was quite needed. I have 2 suggestions:

1. Check if TNS now returns the ID as part of their REST API response
1. Change the readme file, it is quite old and does not represent what the repo actually does

**Comment by myNameIsPatrick** [comment]
@shereenElSayed, thanks for the review. I can update the README to reflect that it's also processing TNS objects now. For checking the TNS IDs, would you be okay with punting that for a future PR? I can investigate that later today and see if that has been updated.

**Comment by myNameIsPatrick** [comment]
@shereenElSayed, the README has been updated. Also looks like the object ID is not available yet, but may be soon.

**Comment by shereenElSayed** [comment]
Thanks Patrick, I guess you are ready to go

**Pull request merged**
